[2018-06-28T17:34:46.365] [ERROR] error - 
        POST 
        /users/login 
        401 
        req: {} 
        res: {"code":"401","message":"token不存在或已过期"}
        errMsg: Authentication Error
        errStack: UnauthorizedError: Authentication Error
    at Object.throw (/Users/xugang/mywork/vue/JYblog/server/node_modules/koa/lib/context.js:93:11)
    at jwt (/Users/xugang/mywork/vue/JYblog/server/node_modules/koa-jwt/lib/index.js:22:22)
    at /Users/xugang/mywork/vue/JYblog/server/node_modules/koa-unless/index.js:49:12
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/koa-compose/index.js:42:32)
    at next (/Users/xugang/mywork/vue/JYblog/server/node_modules/koa-compose/index.js:43:18)
    at /Users/xugang/mywork/vue/JYblog/server/src/middleware/log/index.js:7:12
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/koa-compose/index.js:42:32)
    at next (/Users/xugang/mywork/vue/JYblog/server/node_modules/koa-compose/index.js:43:18)
    at /Users/xugang/mywork/vue/JYblog/server/src/middleware/error/index.js:12:19
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/koa-compose/index.js:42:32)
    
[2018-06-28T17:35:53.155] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {} 
        res: 
        errMsg: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
        errStack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
    at Query.Sequence._packetToError (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:22:28)
    at Handshake.onConnect [as _callback] (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Pool.js:64:7)
    at Handshake.Sequence.end (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Handshake.Sequence.OkPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    
[2018-06-28T17:44:04.685] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {} 
        res: 
        errMsg: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
        errStack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
    at Query.Sequence._packetToError (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:22:28)
    at Handshake.onConnect [as _callback] (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Pool.js:64:7)
    at Handshake.Sequence.end (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Handshake.Sequence.OkPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    
[2018-06-28T17:45:17.704] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {} 
        res: 
        errMsg: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
        errStack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
    at Query.Sequence._packetToError (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:22:28)
    at Handshake.onConnect [as _callback] (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Pool.js:64:7)
    at Handshake.Sequence.end (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Handshake.Sequence.OkPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    
[2018-06-28T22:32:02.339] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {} 
        res: 
        errMsg: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
        errStack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
    at Query.Sequence._packetToError (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:22:28)
    at Ping.onOperationComplete [as _callback] (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.Sequence.end (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Ping.Sequence.OkPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    
[2018-06-28T22:34:34.705] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {} 
        res: 
        errMsg: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
        errStack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
    at Query.Sequence._packetToError (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:22:28)
    at Ping.onOperationComplete [as _callback] (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.Sequence.end (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Ping.Sequence.OkPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    
[2018-06-28T22:35:24.516] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {} 
        res: 
        errMsg: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
        errStack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
    at Query.Sequence._packetToError (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:22:28)
    at Ping.onOperationComplete [as _callback] (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.Sequence.end (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Ping.Sequence.OkPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    
[2018-06-28T22:37:21.177] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {} 
        res: 
        errMsg: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
        errStack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
    at Query.Sequence._packetToError (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:22:28)
    at Ping.onOperationComplete [as _callback] (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.Sequence.end (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Ping.Sequence.OkPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    
[2018-06-28T22:38:33.069] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {"userName":"xugang","password":"123456"} 
        res: 
        errMsg: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
        errStack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user_name' in 'field list'
    at Query.Sequence._packetToError (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:22:28)
    at Ping.onOperationComplete [as _callback] (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.Sequence.end (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Ping.Sequence.OkPacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/xugang/mywork/vue/JYblog/server/node_modules/mysql/lib/Connection.js:103:28)
    
[2018-09-21T15:53:10.138] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {"userName":"15827601003","password":"123456"} 
        res: 
        errMsg: connect ECONNREFUSED 127.0.0.1:3306
        errStack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/Pool.js:48:16)
    at Promise (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:18:14)
    at new Promise (<anonymous>)
    at Object.query [as QUERY] (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:17:12)
    at Object.login [as LOGIN] (/Users/xugang/mywork/vue/JYblog/server/src/models/user.js:32:30)
    at login (/Users/xugang/mywork/vue/JYblog/server/src/controller/user.js:102:20)
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/.3.2.1@koa-compose/index.js:44:32)
    
[2018-09-21T15:53:11.817] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {"userName":"15827601003","password":"123456"} 
        res: 
        errMsg: connect ECONNREFUSED 127.0.0.1:3306
        errStack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/Pool.js:48:16)
    at Promise (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:18:14)
    at new Promise (<anonymous>)
    at Object.query [as QUERY] (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:17:12)
    at Object.login [as LOGIN] (/Users/xugang/mywork/vue/JYblog/server/src/models/user.js:32:30)
    at login (/Users/xugang/mywork/vue/JYblog/server/src/controller/user.js:102:20)
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/.3.2.1@koa-compose/index.js:44:32)
    
[2018-09-21T15:53:21.423] [ERROR] error - 
        POST 
        /user/login 
        500 
        req: {"userName":"15827601003","password":"123456"} 
        res: 
        errMsg: connect ECONNREFUSED 127.0.0.1:3306
        errStack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
    --------------------
    at Protocol._enqueue (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.16.0@mysql/lib/Pool.js:48:16)
    at Promise (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:18:14)
    at new Promise (<anonymous>)
    at Object.query [as QUERY] (/Users/xugang/mywork/vue/JYblog/server/src/util/mysql.js:17:12)
    at Object.login [as LOGIN] (/Users/xugang/mywork/vue/JYblog/server/src/models/user.js:32:30)
    at login (/Users/xugang/mywork/vue/JYblog/server/src/controller/user.js:102:20)
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/.3.2.1@koa-compose/index.js:44:32)
    
[2018-09-21T15:55:41.770] [ERROR] error - 
        GET 
        /articles/system/qiniu 
        401 
        req: {} 
        res: {"code":"401","message":"token不存在或已过期"}
        errMsg: Authentication Error
        errStack: UnauthorizedError: Authentication Error
    at Object.throw (/Users/xugang/mywork/vue/JYblog/server/node_modules/.2.5.3@koa/lib/context.js:96:11)
    at jwt (/Users/xugang/mywork/vue/JYblog/server/node_modules/.3.5.1@koa-jwt/lib/index.js:23:22)
    at /Users/xugang/mywork/vue/JYblog/server/node_modules/.1.0.7@koa-unless/index.js:29:12
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /Users/xugang/mywork/vue/JYblog/server/src/middleware/log/index.js:7:12
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /Users/xugang/mywork/vue/JYblog/server/src/middleware/error/index.js:12:19
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /Users/xugang/mywork/vue/JYblog/server/src/middleware/json/index.js:9:9
    at dispatch (/Users/xugang/mywork/vue/JYblog/server/node_modules/.4.1.0@koa-compose/index.js:42:32)
    
